# Generated by Django 5.2.5 on 2025-08-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webtoon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "capa",
                    models.ImageField(
                        help_text="A imagem de capa da webtoon", upload_to="capas/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("hiato", "Hiato"),
                        ],
                        default="em_andamento",
                        max_length=20,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Capitulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("titulo", models.CharField(blank=True, max_length=200)),
                ("data_publicacao", models.DateTimeField(auto_now_add=True)),
                (
                    "webtoon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capitulos",
                        to="webtoons.webtoon",
                    ),
                ),
            ],
            options={
                "ordering": ["-numero"],
            },
        ),
    ]
