# Generated by Django 5.2.5 on 2025-08-20 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webtoons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="paginas/")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        help_text="A ordem da página no capítulo"
                    ),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paginas",
                        to="webtoons.capitulo",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
    ]
